version: '3.9'

services:

  daylyjournal:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
    environment:
      - CONNECTIONSTRING=mongodb://root:password@mongo:27017/post?authSource=admin

  mongo:
    container_name: my-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongodb: